### ISSUE TITLE
Dia de los Muertos Push

### ISSUE THREAD

**Issue by tothebeat** [vivelohoy/vivelohoy-3.0#182]
These are the features we plan to push on Thursday, October 30:

- [x] Enfoque/Medium-style Post Type
  - [x] Manually create Custom Post Type and Custom Fields #180 
  - [x] Documentation for staff to create Enfoque posts #183
    - [x] Transferred to Google Doc: https://docs.google.com/document/d/1C4znuhKVXaohnU_CPhKRiCo3EdOChgWJ8FAsS8eg0xQ/edit?usp=sharing
- [x] Patrocinado/Sponsored Post Type
  - [x] Manually create Custom Post Type and Custom Fields #181
  - [x] Documentation for Ads department #176
    - [x] Transferred to Google Doc: https://docs.google.com/document/d/1lJMHr3VhVnv7TVIh5k4i-CLBAp3ubjqF6R-sOuNWfLA/edit?usp=sharing
  - [ ] Rules for use by Ads department (at Editor level)
    - [ ] Transferred to Google Doc
  - [x] User created for Ads department to use #179
  - [x] Distinctive styling of Sponsored Post on post itself and home page loop
- [x] Editors can create users
  - [x] Documentation on creating users #184
    - [x] Transferred to Google Doc: https://docs.google.com/document/d/1-R9VBhkvItzRt6naKNbLZ3NjgFHclSAEAJ-CO6G_jsM/edit?usp=sharing
- [x] Activate JetPack Publicize on Production
  - [x] Documentation on how staff can activate accounts and use this #178
    - [x] Transferred to Google Doc: https://docs.google.com/document/d/1OL4pOhpxrg8n9YSsfzc3QxASnMxWhd7ihHx9Csj_8ao/edit?usp=sharing
